import mongoose from 'mongoose';
import dotenv from 'dotenv';
import User from '../models/User.js';
import Category from '../models/Category.js';
import Product from '../models/Product.js';
import Testimonial from '../models/Testimonial.js';
import FAQ from '../models/FAQ.js';
import Subscriber from '../models/Subscriber.js';
import SiteSettings from '../models/SiteSettings.js';
import Coupon from '../models/Coupon.js';

const imageUrls = [
  'https://images.unsplash.com/photo-1759544632264-a31a9ff1e60b?w=800',
  'https://images.unsplash.com/photo-1693387359607-f48d0a824b1e?w=800',
  'https://images.unsplash.com/photo-1679847628912-4c3e7402abc7?w=800',
  'https://images.unsplash.com/photo-1529636798458-92182e662485?w=800',
  'https://images.unsplash.com/photo-1648005539099-709d5be525fb?w=800',
  'https://images.unsplash.com/photo-1693387369575-df25ef8424e7?w=800',
  'https://images.unsplash.com/photo-1747856056384-ba35f5ed353d?w=800',
  'https://images.unsplash.com/photo-1728372923987-15d70bc4946a?w=800',
  'https://images.unsplash.com/photo-1766560359503-dc05c91109f2?w=800',
  'https://images.unsplash.com/photo-1675273316258-0519f62da0d0?w=800',
];

export const seed = async () => {
  await User.deleteMany({});
  await Category.deleteMany({});
  await Product.deleteMany({});
  await Testimonial.deleteMany({});
  await FAQ.deleteMany({});
  await Subscriber.deleteMany({});
  await SiteSettings.deleteMany({});
  await Coupon.deleteMany({});

  const admin1 = await User.create({
    name: 'Sarah Mitchell',
    email: 'admin@joyfulcrotchets.com',
    password: 'Admin123!',
    role: 'admin',
    phone: '555-0101',
    isEmailVerified: true,
  });

  const admin2 = await User.create({
    name: 'Emily Chen',
    email: 'admin2@joyfulcrotchets.com',
    password: 'Admin123!',
    role: 'admin',
    phone: '555-0102',
    isEmailVerified: true,
  });

  const customers = await User.create([
    {
      name: 'Jessica Thompson',
      email: 'jessica@example.com',
      password: 'Customer123!',
      role: 'customer',
      phone: '555-0201',
      isEmailVerified: true,
    },
    {
      name: 'Maria Garcia',
      email: 'maria@example.com',
      password: 'Customer123!',
      role: 'customer',
      phone: '555-0202',
      isEmailVerified: true,
    },
    {
      name: 'Ashley Williams',
      email: 'ashley@example.com',
      password: 'Customer123!',
      role: 'customer',
      phone: '555-0203',
      isEmailVerified: true,
    },
    {
      name: 'Rachel Kim',
      email: 'rachel@example.com',
      password: 'Customer123!',
      role: 'customer',
      phone: '555-0204',
      isEmailVerified: true,
    },
    {
      name: 'Laura Martinez',
      email: 'laura@example.com',
      password: 'Customer123!',
      role: 'customer',
      phone: '555-0205',
      isEmailVerified: true,
    },
  ]);

  const categories = await Category.create([
    { name: 'Bags & Totes', description: 'Handcrafted crochet bags and totes for every occasion', sortOrder: 1, seoTitle: 'Crochet Bags & Totes | Joyful Crotchets', seoDescription: 'Shop our collection of handmade crochet bags and totes', image: { url: 'https://images.unsplash.com/photo-1759544632264-a31a9ff1e60b?w=600&q=80', publicId: '' } },
    { name: 'Bucket Hats', description: 'Trendy and cozy crochet bucket hats', sortOrder: 2, image: { url: 'https://images.unsplash.com/photo-1693387359607-f48d0a824b1e?w=600&q=80', publicId: '' } },
    { name: 'Clothing', description: 'Beautiful handmade crochet clothing pieces', sortOrder: 3, image: { url: 'https://images.unsplash.com/photo-1679847628912-4c3e7402abc7?w=600&q=80', publicId: '' } },
    { name: 'Flowers & Botanicals', description: 'Lifelike crochet flowers and botanical arrangements', sortOrder: 4, image: { url: 'https://images.unsplash.com/photo-1529636798458-92182e662485?w=600&q=80', publicId: '' } },
    { name: 'Plushies & Toys', description: 'Adorable crochet plushies and toys for all ages', sortOrder: 5, image: { url: 'https://images.unsplash.com/photo-1648005539099-709d5be525fb?w=600&q=80', publicId: '' } },
    { name: 'Blankets & Throws', description: 'Cozy crochet blankets and throws for your home', sortOrder: 6, image: { url: 'https://images.unsplash.com/photo-1693387369575-df25ef8424e7?w=600&q=80', publicId: '' } },
    { name: 'Home Décor', description: 'Stylish crochet home decoration items', sortOrder: 7, image: { url: 'https://images.unsplash.com/photo-1747856056384-ba35f5ed353d?w=600&q=80', publicId: '' } },
    { name: 'Baby Collection', description: 'Soft and safe crochet items for babies', sortOrder: 8, image: { url: 'https://images.unsplash.com/photo-1728372923987-15d70bc4946a?w=600&q=80', publicId: '' } },
    { name: 'Accessories', description: 'Complete your look with crochet accessories', sortOrder: 9, image: { url: 'https://images.unsplash.com/photo-1766560359503-dc05c91109f2?w=600&q=80', publicId: '' } },
    { name: 'Key Holders', description: 'Cute and functional crochet key holders', sortOrder: 10, image: { url: 'https://images.unsplash.com/photo-1675273316258-0519f62da0d0?w=600&q=80', publicId: '' } },
    { name: 'Custom Orders', description: 'Request a custom crochet creation', sortOrder: 11, image: { url: 'https://images.unsplash.com/photo-1693326873444-d7cf33cad3e0?w=600&q=80', publicId: '' } },
  ]);

  const catMap = {};
  categories.forEach((c) => { catMap[c.name] = c._id; });

  const products = await Product.create([
    {
      name: 'Boho Macramé Tote Bag',
      description: 'A stunning bohemian-style macramé tote bag, perfect for beach trips or farmers market runs. Handwoven with premium cotton cord featuring intricate knot patterns and leather handles. Spacious interior with a secure snap closure.',
      shortDescription: 'Handwoven macramé tote with leather handles',
      price: 68.00,
      compareAtPrice: 85.00,
      category: catMap['Bags & Totes'],
      images: [{ url: imageUrls[0], alt: 'Boho Macramé Tote Bag', isPrimary: true }],
      colors: [
        { name: 'Natural', hex: '#F5F0E8', inStock: true },
        { name: 'Sand', hex: '#C2B280', inStock: true },
        { name: 'Charcoal', hex: '#36454F', inStock: true },
      ],
      materials: ['Cotton Cord', 'Genuine Leather'],
      dimensions: { length: 40, width: 35, height: 15, unit: 'cm' },
      weight: 350,
      stock: 25,
      sold: 87,
      isPublished: true,
      isFeatured: true,
      isBestSeller: true,
      tags: ['boho', 'macramé', 'tote', 'beach bag', 'handmade'],
      careInstructions: 'Spot clean with damp cloth. Air dry flat.',
      estimatedDelivery: '3-5 business days',
      customizationOptions: {
        allowsCustomization: true,
        customizationNote: 'Custom colors and handle lengths available upon request',
        additionalPrice: 15.00,
        estimatedDays: 7,
      },
      averageRating: 4.8,
      numReviews: 42,
    },
    {
      name: 'Sunset Gradient Bucket Hat',
      description: 'A vibrant crochet bucket hat featuring a gorgeous sunset gradient from warm coral to golden yellow. Lightweight and perfect for summer adventures. One size fits most with an adjustable inner band.',
      shortDescription: 'Gradient sunset-colored crochet bucket hat',
      price: 32.00,
      category: catMap['Bucket Hats'],
      images: [{ url: imageUrls[1], alt: 'Sunset Gradient Bucket Hat', isPrimary: true }],
      colors: [
        { name: 'Sunset', hex: '#FF6B35', inStock: true },
        { name: 'Ocean', hex: '#4ECDC4', inStock: true },
        { name: 'Lavender', hex: '#9B59B6', inStock: true },
      ],
      materials: ['Cotton Yarn'],
      dimensions: { length: 28, width: 28, height: 12, unit: 'cm' },
      weight: 80,
      stock: 40,
      sold: 124,
      isPublished: true,
      isFeatured: true,
      isNewArrival: true,
      tags: ['bucket hat', 'summer', 'gradient', 'trendy'],
      careInstructions: 'Hand wash cold. Reshape and lay flat to dry.',
      averageRating: 4.6,
      numReviews: 58,
    },
    {
      name: 'Floral Cardigan Wrap',
      description: 'An elegant crochet cardigan wrap adorned with delicate floral motifs. Perfect for layering over dresses or jeans. Made from soft bamboo blend yarn that drapes beautifully.',
      shortDescription: 'Elegant floral crochet cardigan wrap',
      price: 95.00,
      compareAtPrice: 120.00,
      category: catMap['Clothing'],
      images: [{ url: imageUrls[2], alt: 'Floral Cardigan Wrap', isPrimary: true }],
      colors: [
        { name: 'Blush Pink', hex: '#FFB6C1', inStock: true },
        { name: 'Sage Green', hex: '#BCB88A', inStock: true },
        { name: 'Cream', hex: '#FFFDD0', inStock: true },
      ],
      materials: ['Bamboo Yarn', 'Cotton Blend'],
      dimensions: { length: 65, width: 50, height: 0, unit: 'cm' },
      weight: 280,
      stock: 15,
      sold: 45,
      isPublished: true,
      isFeatured: true,
      tags: ['cardigan', 'wrap', 'floral', 'elegant', 'layering'],
      careInstructions: 'Hand wash in cold water. Lay flat to dry.',
      estimatedDelivery: '3-5 business days',
      averageRating: 4.9,
      numReviews: 23,
    },
    {
      name: 'Crochet Rose Bouquet Set',
      description: 'A stunning set of 12 handcrafted crochet roses in assorted colors. These everlasting blooms make the perfect gift for anniversaries, birthdays, or just because. Each rose is individually crafted with realistic petal details.',
      shortDescription: 'Set of 12 handmade crochet roses',
      price: 45.00,
      category: catMap['Flowers & Botanicals'],
      images: [{ url: imageUrls[3], alt: 'Crochet Rose Bouquet Set', isPrimary: true }],
      colors: [
        { name: 'Red', hex: '#FF0000', inStock: true },
        { name: 'Pink', hex: '#FFC0CB', inStock: true },
        { name: 'White', hex: '#FFFFFF', inStock: true },
        { name: 'Mixed', hex: '#FF69B4', inStock: true },
      ],
      materials: ['Acrylic Yarn', 'Floral Wire', 'Green Tape'],
      dimensions: { length: 30, width: 20, height: 10, unit: 'cm' },
      weight: 200,
      stock: 30,
      sold: 203,
      isPublished: true,
      isBestSeller: true,
      tags: ['roses', 'flowers', 'bouquet', 'gift', 'everlasting'],
      careInstructions: 'Dust gently with a soft brush.',
      estimatedDelivery: '3-5 business days',
      averageRating: 4.9,
      numReviews: 89,
    },
    {
      name: 'Amigurumi Teddy Bear',
      description: 'An adorable hand-crocheted teddy bear made with hypoallergenic cotton stuffing. Features embroidered eyes and a sweet bow tie. Perfect as a nursery decoration or a cuddly companion for children.',
      shortDescription: 'Handmade crochet teddy bear plushie',
      price: 38.00,
      category: catMap['Plushies & Toys'],
      images: [{ url: imageUrls[4], alt: 'Amigurumi Teddy Bear', isPrimary: true }],
      colors: [
        { name: 'Honey Brown', hex: '#DAA520', inStock: true },
        { name: 'Cream', hex: '#FFFDD0', inStock: true },
        { name: 'Gray', hex: '#808080', inStock: true },
      ],
      materials: ['Cotton Yarn', 'Hypoallergenic Polyester Fill'],
      dimensions: { length: 25, width: 15, height: 20, unit: 'cm' },
      weight: 150,
      stock: 20,
      sold: 156,
      isPublished: true,
      isFeatured: true,
      isBestSeller: true,
      tags: ['teddy bear', 'amigurumi', 'plushie', 'toy', 'nursery'],
      careInstructions: 'Hand wash gently. Air dry.',
      estimatedDelivery: '5-7 business days',
      averageRating: 4.7,
      numReviews: 67,
    },
    {
      name: 'Chunky Knit Throw Blanket',
      description: 'A luxurious chunky crochet throw blanket that brings warmth and texture to any space. Made with ultra-soft chenille yarn in a timeless basketweave pattern. Generously sized for couches and beds.',
      shortDescription: 'Luxurious chunky chenille throw blanket',
      price: 125.00,
      compareAtPrice: 155.00,
      category: catMap['Blankets & Throws'],
      images: [{ url: imageUrls[5], alt: 'Chunky Knit Throw Blanket', isPrimary: true }],
      colors: [
        { name: 'Oatmeal', hex: '#D3C2A2', inStock: true },
        { name: 'Dusty Rose', hex: '#DCAE96', inStock: true },
        { name: 'Slate', hex: '#708090', inStock: true },
      ],
      materials: ['Chenille Yarn'],
      dimensions: { length: 150, width: 120, height: 0, unit: 'cm' },
      weight: 1200,
      stock: 12,
      sold: 34,
      isPublished: true,
      isFeatured: true,
      tags: ['blanket', 'throw', 'chunky', 'chenille', 'cozy'],
      careInstructions: 'Machine wash cold on gentle cycle. Tumble dry low.',
      estimatedDelivery: '5-7 business days',
      averageRating: 4.8,
      numReviews: 19,
    },
    {
      name: 'Crochet Wall Hanging Mandala',
      description: 'A breathtaking crochet mandala wall hanging that serves as a stunning focal point for any room. Features intricate geometric patterns and fringe details. Includes a wooden dowel for easy hanging.',
      shortDescription: 'Intricate crochet mandala wall art',
      price: 58.00,
      category: catMap['Home Décor'],
      images: [{ url: imageUrls[6], alt: 'Crochet Wall Hanging Mandala', isPrimary: true }],
      colors: [
        { name: 'Boho Rainbow', hex: '#E8A87C', inStock: true },
        { name: 'Earth Tones', hex: '#85677B', inStock: true },
        { name: 'Monochrome', hex: '#2C3E50', inStock: true },
      ],
      materials: ['Cotton Yarn', 'Wooden Dowel'],
      dimensions: { length: 45, width: 45, height: 2, unit: 'cm' },
      weight: 250,
      stock: 18,
      sold: 72,
      isPublished: true,
      isBestSeller: true,
      tags: ['wall hanging', 'mandala', 'boho', 'home décor', 'macramé'],
      careInstructions: 'Spot clean only.',
      estimatedDelivery: '3-5 business days',
      averageRating: 4.7,
      numReviews: 35,
    },
    {
      name: 'Baby Cocoon Sleep Sack',
      description: 'A soft and cozy crochet baby cocoon sleep sack, perfect for newborn photo shoots and keeping your little one snug. Made with premium soft cotton yarn in gentle pastel colors.',
      shortDescription: 'Soft crochet baby cocoon sleep sack',
      price: 42.00,
      category: catMap['Baby Collection'],
      images: [{ url: imageUrls[7], alt: 'Baby Cocoon Sleep Sack', isPrimary: true }],
      colors: [
        { name: 'Soft Pink', hex: '#FFB6C1', inStock: true },
        { name: 'Baby Blue', hex: '#89CFF0', inStock: true },
        { name: 'Vanilla', hex: '#F3E5AB', inStock: true },
      ],
      materials: ['Organic Cotton Yarn'],
      dimensions: { length: 60, width: 30, height: 5, unit: 'cm' },
      weight: 180,
      stock: 22,
      sold: 98,
      isPublished: true,
      isFeatured: true,
      tags: ['baby', 'cocoon', 'newborn', 'photo prop', 'sleep sack'],
      careInstructions: 'Hand wash in lukewarm water. Lay flat to dry.',
      estimatedDelivery: '3-5 business days',
      averageRating: 4.9,
      numReviews: 54,
    },
    {
      name: 'Dainty Pearl Bracelet',
      description: 'A delicate crochet bracelet adorned with freshwater pearls and a gold-tone clasp. Lightweight and elegant, perfect for everyday wear or special occasions.',
      shortDescription: 'Delicate crochet and pearl bracelet',
      price: 28.00,
      category: catMap['Accessories'],
      images: [{ url: imageUrls[8], alt: 'Dainty Pearl Bracelet', isPrimary: true }],
      colors: [
        { name: 'White Pearl', hex: '#FDEEF4', inStock: true },
        { name: 'Gold', hex: '#FFD700', inStock: true },
        { name: 'Rose Gold', hex: '#B76E79', inStock: true },
      ],
      materials: ['Cotton Thread', 'Freshwater Pearls', 'Gold Plated Clasp'],
      dimensions: { length: 18, width: 1, height: 0.5, unit: 'cm' },
      weight: 15,
      stock: 35,
      sold: 145,
      isPublished: true,
      tags: ['bracelet', 'jewelry', 'pearl', 'elegant', 'accessory'],
      careInstructions: 'Avoid contact with water and perfume.',
      averageRating: 4.6,
      numReviews: 78,
    },
    {
      name: 'Cute Cat Keychain',
      description: 'An adorable amigurumi cat keychain that adds personality to your keys or bag. Each cat is hand-crocheted with attention to detail, featuring tiny whiskers and a little bell.',
      shortDescription: 'Handmade amigurumi cat keychain',
      price: 15.00,
      category: catMap['Key Holders'],
      images: [{ url: imageUrls[9], alt: 'Cute Cat Keychain', isPrimary: true }],
      colors: [
        { name: 'Tabby', hex: '#D2691E', inStock: true },
        { name: 'Black', hex: '#000000', inStock: true },
        { name: 'White', hex: '#FFFFFF', inStock: true },
        { name: 'Calico', hex: '#FF7F50', inStock: true },
      ],
      materials: ['Cotton Yarn', 'Metal Keychain Ring', 'Small Bell'],
      dimensions: { length: 8, width: 5, height: 5, unit: 'cm' },
      weight: 20,
      stock: 50,
      sold: 234,
      isPublished: true,
      isBestSeller: true,
      tags: ['keychain', 'cat', 'amigurumi', 'cute', 'gift'],
      careInstructions: 'Spot clean only.',
      averageRating: 4.8,
      numReviews: 112,
    },
    {
      name: 'Crochet Plant Pot Cover',
      description: 'A stylish crochet cover for your plant pots that adds warmth and texture to your indoor garden. Available in various sizes to fit standard pot dimensions. Features a waterproof lining.',
      shortDescription: 'Handmade crochet plant pot cover',
      price: 24.00,
      category: catMap['Home Décor'],
      images: [{ url: imageUrls[0], alt: 'Crochet Plant Pot Cover', isPrimary: true }],
      colors: [
        { name: 'Natural', hex: '#F5F0E8', inStock: true },
        { name: 'Terracotta', hex: '#E2725B', inStock: true },
        { name: 'Forest', hex: '#228B22', inStock: true },
      ],
      materials: ['Cotton Yarn', 'Waterproof Lining'],
      dimensions: { length: 15, width: 15, height: 14, unit: 'cm' },
      weight: 120,
      stock: 30,
      sold: 67,
      isPublished: true,
      tags: ['plant pot', 'cover', 'home décor', 'indoor garden'],
      careInstructions: 'Wipe clean with damp cloth.',
      averageRating: 4.5,
      numReviews: 28,
    },
    {
      name: 'Oversized Beach Poncho',
      description: 'A gorgeous oversized crochet poncho perfect for beach days and breezy evenings. Features a lacy shell stitch pattern and fringe trim. One size fits all with a relaxed drape.',
      shortDescription: 'Lacy crochet beach poncho with fringe',
      price: 78.00,
      compareAtPrice: 95.00,
      category: catMap['Clothing'],
      images: [{ url: imageUrls[2], alt: 'Oversized Beach Poncho', isPrimary: true }],
      colors: [
        { name: 'Sand', hex: '#C2B280', inStock: true },
        { name: 'Coral', hex: '#FF7F50', inStock: true },
        { name: 'Turquoise', hex: '#40E0D0', inStock: true },
      ],
      materials: ['Cotton Yarn'],
      dimensions: { length: 80, width: 70, height: 0, unit: 'cm' },
      weight: 350,
      stock: 18,
      sold: 41,
      isPublished: true,
      tags: ['poncho', 'beach', 'cover-up', 'lacy', 'summer'],
      careInstructions: 'Hand wash cold. Lay flat to dry.',
      averageRating: 4.7,
      numReviews: 16,
    },
    {
      name: 'Luna the Bunny Plush',
      description: 'Meet Luna, the sweetest crochet bunny with floppy ears and a fluffy tail. Made with ultra-soft velvet yarn, this plushie is perfect for cuddling. Includes a tiny removable bow.',
      shortDescription: 'Velvet yarn crochet bunny plushie',
      price: 44.00,
      category: catMap['Plushies & Toys'],
      images: [{ url: imageUrls[4], alt: 'Luna the Bunny Plush', isPrimary: true }],
      colors: [
        { name: 'Blush', hex: '#FFB6C1', inStock: true },
        { name: 'Lilac', hex: '#C8A2C8', inStock: true },
        { name: 'Mint', hex: '#98FF98', inStock: true },
      ],
      materials: ['Velvet Yarn', 'Polyester Fill', 'Safety Eyes'],
      dimensions: { length: 30, width: 15, height: 25, unit: 'cm' },
      weight: 200,
      stock: 16,
      sold: 89,
      isPublished: true,
      isNewArrival: true,
      tags: ['bunny', 'plushie', 'velvet', 'amigurumi', 'gift'],
      careInstructions: 'Hand wash gently. Air dry.',
      estimatedDelivery: '5-7 business days',
      averageRating: 4.9,
      numReviews: 34,
    },
    {
      name: 'Boho Dream Catcher',
      description: 'A handcrafted bohemian dream catcher with intricate crochet web and flowing ribbons. Hang it above your bed for a whimsical touch. Features genuine feathers and wooden beads.',
      shortDescription: 'Handmade boho dream catcher',
      price: 35.00,
      category: catMap['Home Décor'],
      images: [{ url: imageUrls[6], alt: 'Boho Dream Catcher', isPrimary: true }],
      colors: [
        { name: 'White', hex: '#FFFFFF', inStock: true },
        { name: 'Natural', hex: '#F5F0E8', inStock: true },
        { name: 'Dusty Pink', hex: '#DCAE96', inStock: true },
      ],
      materials: ['Cotton Thread', 'Metal Ring', 'Genuine Feathers', 'Wooden Beads'],
      dimensions: { length: 20, width: 20, height: 45, unit: 'cm' },
      weight: 100,
      stock: 24,
      sold: 56,
      isPublished: true,
      tags: ['dream catcher', 'boho', 'wall décor', 'bedroom'],
      careInstructions: 'Dust gently. Keep away from moisture.',
      averageRating: 4.6,
      numReviews: 22,
    },
    {
      name: 'Baby Booties Gift Set',
      description: 'A precious set of three pairs of crochet baby booties in graduated sizes (0-3m, 3-6m, 6-12m). Each pair features a different stitch pattern and comes in a beautiful gift box.',
      shortDescription: 'Set of 3 pairs crochet baby booties',
      price: 52.00,
      compareAtPrice: 65.00,
      category: catMap['Baby Collection'],
      images: [{ url: imageUrls[7], alt: 'Baby Booties Gift Set', isPrimary: true }],
      colors: [
        { name: 'Pastel Rainbow', hex: '#FFB6C1', inStock: true },
        { name: 'Neutral', hex: '#F5F0E8', inStock: true },
      ],
      materials: ['Soft Cotton Yarn', 'Ribbon'],
      dimensions: { length: 15, width: 8, height: 8, unit: 'cm' },
      weight: 100,
      stock: 20,
      sold: 76,
      isPublished: true,
      isFeatured: true,
      tags: ['baby booties', 'gift set', 'newborn', 'baby shower'],
      careInstructions: 'Hand wash in lukewarm water.',
      estimatedDelivery: '3-5 business days',
      averageRating: 4.8,
      numReviews: 41,
    },
    {
      name: 'Crochet Headband Ear Warmer',
      description: 'A cozy wide crochet headband that keeps your ears warm in style. Features a twisted knot design and is made with soft acrylic yarn. Great for cold weather and bad hair days.',
      shortDescription: 'Twisted knot crochet ear warmer',
      price: 18.00,
      category: catMap['Accessories'],
      images: [{ url: imageUrls[8], alt: 'Crochet Headband', isPrimary: true }],
      colors: [
        { name: 'Burgundy', hex: '#800020', inStock: true },
        { name: 'Forest Green', hex: '#228B22', inStock: true },
        { name: 'Camel', hex: '#C19A6B', inStock: true },
        { name: 'Charcoal', hex: '#36454F', inStock: true },
      ],
      materials: ['Acrylic Yarn'],
      dimensions: { length: 22, width: 10, height: 2, unit: 'cm' },
      weight: 50,
      stock: 45,
      sold: 167,
      isPublished: true,
      isBestSeller: true,
      tags: ['headband', 'ear warmer', 'winter', 'twisted'],
      careInstructions: 'Hand wash cold. Lay flat to dry.',
      averageRating: 4.5,
      numReviews: 93,
    },
    {
      name: 'Crochet Coaster Set (6)',
      description: 'A set of six beautiful crochet coasters in coordinating colors. Made with absorbent cotton yarn in a vintage-inspired flower pattern. Protects surfaces while adding charm.',
      shortDescription: 'Set of 6 vintage flower crochet coasters',
      price: 22.00,
      category: catMap['Home Décor'],
      images: [{ url: imageUrls[9], alt: 'Crochet Coaster Set', isPrimary: true }],
      colors: [
        { name: 'Sunset Mix', hex: '#FF6B35', inStock: true },
        { name: 'Ocean Mix', hex: '#4ECDC4', inStock: true },
        { name: 'Neutral Mix', hex: '#D3C2A2', inStock: true },
      ],
      materials: ['Cotton Yarn'],
      dimensions: { length: 10, width: 10, height: 0.5, unit: 'cm' },
      weight: 80,
      stock: 35,
      sold: 112,
      isPublished: true,
      tags: ['coasters', 'home décor', 'vintage', 'flower', 'set'],
      careInstructions: 'Machine wash cold. Tumble dry low.',
      averageRating: 4.7,
      numReviews: 55,
    },
    {
      name: 'Custom Pet Portrait',
      description: 'Get a custom-made crochet portrait of your beloved pet! Simply provide a clear photo and we will create a stunning yarn representation. Each portrait is unique and captures your pet\'s personality.',
      shortDescription: 'Custom crochet pet portrait from your photo',
      price: 180.00,
      category: catMap['Custom Orders'],
      images: [{ url: imageUrls[3], alt: 'Custom Pet Portrait', isPrimary: true }],
      materials: ['Premium Acrylic Yarn', 'Canvas Frame'],
      dimensions: { length: 30, width: 30, height: 2, unit: 'cm' },
      stock: 0,
      sold: 28,
      isPublished: true,
      tags: ['custom', 'pet portrait', 'personalized', 'gift'],
      careInstructions: 'Dust with soft brush. Keep away from direct sunlight.',
      estimatedDelivery: '2-3 weeks',
      customizationOptions: {
        allowsCustomization: true,
        customizationNote: 'Upload a clear photo of your pet. Specify any size preferences.',
        additionalPrice: 0,
        estimatedDays: 14,
      },
      averageRating: 5.0,
      numReviews: 28,
    },
    {
      name: 'Market String Bag',
      description: 'An eco-friendly expandable crochet market bag that folds small enough to fit in your pocket. Stretches to hold a surprising amount of groceries or market finds. Made with durable cotton cord.',
      shortDescription: 'Expandable eco-friendly crochet market bag',
      price: 26.00,
      category: catMap['Bags & Totes'],
      images: [{ url: imageUrls[0], alt: 'Market String Bag', isPrimary: true }],
      colors: [
        { name: 'Natural', hex: '#F5F0E8', inStock: true },
        { name: 'Olive', hex: '#808000', inStock: true },
      ],
      materials: ['Cotton Cord'],
      dimensions: { length: 35, width: 35, height: 0, unit: 'cm' },
      weight: 120,
      stock: 40,
      sold: 189,
      isPublished: true,
      isBestSeller: true,
      tags: ['market bag', 'eco-friendly', 'reusable', 'string bag'],
      careInstructions: 'Machine wash cold. Hang to dry.',
      averageRating: 4.6,
      numReviews: 102,
    },
    {
      name: 'Cuddle Bear Blanket',
      description: 'An adorable blanket with a built-in bear hood, perfect for toddlers. Combines the warmth of a crochet blanket with the fun of a costume. Great for photos and cozy nap times.',
      shortDescription: 'Toddler blanket with built-in bear hood',
      price: 55.00,
      category: catMap['Baby Collection'],
      images: [{ url: imageUrls[5], alt: 'Cuddle Bear Blanket', isPrimary: true }],
      colors: [
        { name: 'Teddy Brown', hex: '#D2691E', inStock: true },
        { name: 'Polar White', hex: '#F8F8FF', inStock: true },
      ],
      materials: ['Soft Acrylic Yarn'],
      dimensions: { length: 100, width: 80, height: 0, unit: 'cm' },
      weight: 400,
      stock: 15,
      sold: 63,
      isPublished: true,
      isNewArrival: true,
      tags: ['blanket', 'toddler', 'bear', 'hoodie blanket', 'baby'],
      careInstructions: 'Machine wash on gentle cycle. Tumble dry low.',
      averageRating: 4.8,
      numReviews: 29,
    },
    {
      name: 'Woven Wall Basket Set',
      description: 'A set of three nesting crochet wall baskets that can be hung individually or grouped together. Perfect for organizing small items or as standalone wall art. Includes hanging hardware.',
      shortDescription: 'Set of 3 nesting crochet wall baskets',
      price: 48.00,
      category: catMap['Home Décor'],
      images: [{ url: imageUrls[1], alt: 'Woven Wall Basket Set', isPrimary: true }],
      colors: [
        { name: 'Natural', hex: '#F5F0E8', inStock: true },
        { name: 'Black & White', hex: '#000000', inStock: true },
      ],
      materials: ['Cotton Rope', 'Metal Hardware'],
      dimensions: { length: 30, width: 30, height: 8, unit: 'cm' },
      weight: 300,
      stock: 20,
      sold: 44,
      isPublished: true,
      tags: ['wall basket', 'storage', 'home décor', 'set'],
      careInstructions: 'Wipe clean with damp cloth.',
      averageRating: 4.5,
      numReviews: 18,
    },
  ]);

  const testimonials = await Testimonial.create([
    { customerName: 'Jessica Thompson', content: 'The quality of these crochet pieces is absolutely incredible! My macramé tote has become my everyday bag. The craftsmanship is unmatched.', rating: 5, isFeatured: true, sortOrder: 1 },
    { customerName: 'Maria Garcia', content: 'I ordered the crochet rose bouquet for my mother\'s birthday and she was in tears! They look so realistic and will last forever. Truly special gifts.', rating: 5, isFeatured: true, sortOrder: 2 },
    { customerName: 'Ashley Williams', content: 'The amigurumi teddy bear I purchased for my daughter is her absolute favorite. It\'s beautifully made and so soft. We\'ve already ordered another one!', rating: 5, isFeatured: true, sortOrder: 3 },
    { customerName: 'Rachel Kim', content: 'I\'ve been searching for the perfect crochet bucket hat and found it here! The sunset gradient is even more beautiful in person. Great quality and fast shipping.', rating: 5, isFeatured: true, sortOrder: 4 },
    { customerName: 'Laura Martinez', content: 'The custom pet portrait exceeded all my expectations. The artist captured my dog\'s personality perfectly. I\'ve recommended Joyful Crotchets to all my friends.', rating: 5, isFeatured: true, sortOrder: 5 },
    { customerName: 'Nicole Brown', content: 'Beautiful work and excellent customer service. The baby booties gift set was a huge hit at the baby shower. Will definitely order again!', rating: 5, isFeatured: false, sortOrder: 6 },
    { customerName: 'Emma Davis', content: 'I love my chunky throw blanket! It\'s the perfect weight and the colors are exactly as shown. It has become my favorite thing on the couch.', rating: 5, isFeatured: false, sortOrder: 7 },
    { customerName: 'Sophie Wilson', content: 'The mandala wall hanging is a true work of art. It transformed my living room. The attention to detail is remarkable.', rating: 5, isFeatured: false, sortOrder: 8 },
    { customerName: 'Amanda Taylor', content: 'Fast shipping, beautiful packaging, and the product exceeded my expectations. The headband ear warmer is so cozy and stylish!', rating: 4, isFeatured: false, sortOrder: 9 },
    { customerName: 'Michelle Lee', content: 'I\'ve ordered multiple items and every single one has been perfect. The quality is consistent and the designs are unique. Highly recommend!', rating: 5, isFeatured: true, sortOrder: 10 },
    { customerName: 'Christina White', content: 'The coasters are adorable and so well-made. I bought sets for all my friends as Christmas gifts. Everyone loved them!', rating: 5, isFeatured: false, sortOrder: 11 },
    { customerName: 'Diana Clark', content: 'Beautiful craftsmanship and attention to detail. The floral cardigan is stunning and fits perfectly. Will be ordering more items!', rating: 5, isFeatured: false, sortOrder: 12 },
  ]);

  const faqs = await FAQ.create([
    { question: 'How long does shipping take?', answer: 'Standard shipping takes 3-5 business days within the US. International orders typically take 7-14 business days depending on the destination. Express shipping options are available at checkout.', category: 'Shipping', sortOrder: 1 },
    { question: 'Do you ship internationally?', answer: 'Yes, we ship worldwide! International shipping rates are calculated at checkout based on your location and order weight. Please note that customs duties and taxes may apply.', category: 'Shipping', sortOrder: 2 },
    { question: 'How much is shipping?', answer: 'We offer free standard shipping on all US orders over $75. Standard shipping is $8.99 for orders under $75. Express shipping is available for $14.99. International shipping rates vary.', category: 'Shipping', sortOrder: 3 },
    { question: 'What is your return policy?', answer: 'We accept returns within 14 days of delivery for unused items in original condition. Custom orders are final sale. Please contact us to initiate a return.', category: 'Returns', sortOrder: 4 },
    { question: 'How do I start a return?', answer: 'Email us at returns@joyfulcrotchets.com with your order number and reason for return. We will provide a prepaid return label and instructions. Refunds are processed within 5-7 business days of receiving the return.', category: 'Returns', sortOrder: 5 },
    { question: 'Can I exchange an item?', answer: 'Yes! Exchanges are available within 14 days of delivery. Contact us with your order number and the item you\'d like to exchange for. Subject to availability.', category: 'Returns', sortOrder: 6 },
    { question: 'How do I place a custom order?', answer: 'Click on "Custom Orders" in our menu and fill out the request form with details about your project, including description, preferred colors, dimensions, and budget range. We\'ll review and provide a quote within 48 hours.', category: 'Custom Orders', sortOrder: 7 },
    { question: 'How long do custom orders take?', answer: 'Custom orders typically take 2-4 weeks to complete depending on complexity. We\'ll provide an estimated timeline with your quote. Rush orders may be available for an additional fee.', category: 'Custom Orders', sortOrder: 8 },
    { question: 'Can I request a specific color or size?', answer: 'Absolutely! We love bringing your vision to life. Include color preferences and size specifications in your custom order request. We can also send yarn samples before starting.', category: 'Custom Orders', sortOrder: 9 },
    { question: 'How do I care for my crochet items?', answer: 'Most items are best hand washed in cold water and laid flat to dry. Specific care instructions are included with each product. Avoid wringing or twisting crochet items to maintain their shape.', category: 'Care', sortOrder: 10 },
    { question: 'Will my crochet item pill or shed?', answer: 'Our items are made with high-quality yarns that resist pilling. Some initial shedding may occur with fluffy yarns but decreases with use. We recommend gentle handling for the first few washes.', category: 'Care', sortOrder: 11 },
    { question: 'Can I put crochet items in the washing machine?', answer: 'Some items are machine washable on a gentle cycle with cold water. Always check the specific care instructions included with your product. When in doubt, hand wash to be safe.', category: 'Care', sortOrder: 12 },
    { question: 'Are your products hypoallergenic?', answer: 'We offer products made with hypoallergenic materials including organic cotton and premium acrylic yarns. If you have specific allergies, please let us know and we\'ll recommend the best options.', category: 'General', sortOrder: 13 },
    { question: 'Do you offer wholesale pricing?', answer: 'Yes, we offer wholesale pricing for retailers and boutiques. Please contact us at wholesale@joyfulcrotchets.com with your business details and we\'ll discuss partnership opportunities.', category: 'General', sortOrder: 14 },
    { question: 'Can I request gift wrapping?', answer: 'Yes! We offer beautiful gift wrapping for $5.99. Your gift will include a handwritten note card. Select the gift wrapping option at checkout and add your personal message.', category: 'General', sortOrder: 15 },
    { question: 'How do I track my order?', answer: 'Once your order ships, you\'ll receive an email with a tracking number. You can also log into your account to view order status and tracking information anytime.', category: 'Shipping', sortOrder: 16 },
  ]);

  const subscribers = await Subscriber.create([
    { email: 'jessica@example.com', name: 'Jessica Thompson', isActive: true },
    { email: 'maria@example.com', name: 'Maria Garcia', isActive: true },
    { email: 'ashley@example.com', name: 'Ashley Williams', isActive: true },
    { email: 'rachel@example.com', name: 'Rachel Kim', isActive: true },
    { email: 'laura@example.com', name: 'Laura Martinez', isActive: true },
    { email: 'nicole@example.com', name: 'Nicole Brown', isActive: true },
    { email: 'emma@example.com', name: 'Emma Davis', isActive: true },
    { email: 'sophie@example.com', name: 'Sophie Wilson', isActive: true },
    { email: 'amanda@example.com', name: 'Amanda Taylor', isActive: true },
    { email: 'michelle@example.com', name: 'Michelle Lee', isActive: true },
    { email: 'christina@example.com', name: 'Christina White', isActive: true },
    { email: 'diana@example.com', name: 'Diana Clark', isActive: true },
  ]);

  await SiteSettings.create([
    { key: 'storeName', value: 'Joyful Crotchets', category: 'general' },
    { key: 'storeDescription', value: 'Premium handmade crochet creations crafted with love', category: 'general' },
    { key: 'storeEmail', value: 'hello@joyfulcrotchets.com', category: 'general' },
    { key: 'storePhone', value: '555-0100', category: 'general' },
    { key: 'storeAddress', value: { street: '123 Yarn Lane', city: 'Craftville', state: 'CA', zipCode: '90210', country: 'USA' }, category: 'general' },
    { key: 'socialLinks', value: { instagram: 'https://instagram.com/joyfulcrotchets', facebook: 'https://facebook.com/joyfulcrotchets', pinterest: 'https://pinterest.com/joyfulcrotchets', tiktok: 'https://tiktok.com/@joyfulcrotchets' }, category: 'social' },
    { key: 'shippingRates', value: { freeShippingThreshold: 75, standardRate: 8.99, expressRate: 14.99, internationalBase: 19.99 }, category: 'shipping' },
    { key: 'businessHours', value: { monday: '9:00 AM - 6:00 PM', tuesday: '9:00 AM - 6:00 PM', wednesday: '9:00 AM - 6:00 PM', thursday: '9:00 AM - 6:00 PM', friday: '9:00 AM - 5:00 PM', saturday: '10:00 AM - 4:00 PM', sunday: 'Closed' }, category: 'general' },
    { key: 'taxRate', value: 0.08, category: 'shipping' },
    { key: 'currency', value: 'USD', category: 'general' },
  ]);

  const coupons = await Coupon.create([
    { code: 'WELCOME10', description: '10% off your first order', discountType: 'percentage', discountValue: 10, minPurchase: 30, isActive: true, expiresAt: new Date('2025-12-31'), usageLimit: 500 },
    { code: 'SUMMER15', description: '15% off summer collection', discountType: 'percentage', discountValue: 15, minPurchase: 50, isActive: true, expiresAt: new Date('2025-09-30'), usageLimit: 200 },
    { code: 'FREE20', description: '$20 off orders over $100', discountType: 'fixed', discountValue: 20, minPurchase: 100, isActive: true, usageLimit: 300 },
    { code: 'JOYFUL5', description: '$5 off any order', discountType: 'fixed', discountValue: 5, minPurchase: 25, isActive: true, usageLimit: 1000 },
  ]);

  return { users: 2 + customers.length, categories: categories.length, products: products.length, testimonials: testimonials.length, faqs: faqs.length, subscribers: subscribers.length, coupons: coupons.length };
};

if (process.argv[1] && process.argv[1].endsWith('seed.js')) {
  dotenv.config();
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('MongoDB connected for seeding...');
  const result = await seed();
  console.log('Seeding completed:', result);
  process.exit(0);
}
